In [1]:
# Import libraries
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import warnings

from scipy.integrate import odeint
from IPython.display import Image
from statistics import mode
from scipy.stats import pearsonr, spearmanr
from sklearn.feature_selection import mutual_info_regression
import statsmodels.api as sm
import pingouin as pg

# Suppress warnings
warnings.filterwarnings('ignore')

# Set number of decimals for np print options
np.set_printoptions(precision=3)

# Set the current working directory
os.chdir(sys.path[0])

In [2]:
df = pd.read_excel('/Users/ombadi/Desktop/Mo Files/Research/GAGES_II/gagesII_metadata.xlsx')

In [3]:
df = df[df['CLASS']=='Ref']

In [4]:
df

,STAID,STANAME,DRAIN_SQKM,HUC02,LAT_GAGE,LNG_GAGE,STATE,BOUND_SOURCE,HCDN-2009,HBN36,...,PET,STREAMS_KM_SQ_KM,BFI_AVE,CONTACT,NDAMS_2009,DDENS_2009,STOR_NID_2009,STOR_NOR_2009,MAJ_NDAMS_2009,MAJ_DDENS_2009
1,1013500,"Fish River near Fort Kent, Maine",2252.69600,01,47.237394,-68.582642,ME,3,yes,NaN,...,504.7188,0.665657,53.61105,244.82490,3,0.133174,0.810069,0.769019,0,0.0
7,1017550,"Williams Brook at Phair, Maine",10.03230,01,46.628056,-67.953056,ME,1,NaN,NaN,...,539.1210,0.255788,54.00000,521.37020,0,0.000000,0.000000,0.000000,0,0.0
13,1021470,"Libby Brook near Northfield, Maine",16.10010,01,44.800833,-67.725000,ME,1,NaN,NaN,...,543.8809,0.509095,54.91011,84.26670,0,0.000000,0.000000,0.000000,0,0.0
14,1021480,"Old Stream near Wesley, Maine",76.73849,01,44.936944,-67.736111,ME,1,NaN,NaN,...,554.1586,0.762407,56.21907,345.15660,0,0.000000,0.000000,0.000000,0,0.0
16,1022260,"Pleasant River near Epping, Maine",161.99370,01,44.697778,-67.787222,ME,1,NaN,NaN,...,548.6202,0.739033,52.83580,658.02940,1,0.617308,27.058552,18.039035,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9047,14362250,"STAR GULCH NEAR RUCH, OR.",41.42160,17,42.154014,-123.075323,OR,1,yes,NaN,...,590.0961,0.755973,58.56905,11.14974,0,0.000000,0.000000,0.000000,0,0.0
9050,14371500,"GRAVE CREEK AT PEASE BRIDGE,NEAR PLACER,OREG.",63.22320,17,42.641510,-123.212281,OR,1,NaN,NaN,...,620.5881,0.665071,44.45135,14.49776,0,0.000000,0.000000,0.000000,0,0.0
9052,14372500,"E F ILLINOIS RIVER NEAR TAKILMA,OREG.",140.06070,17,42.069281,-123.626178,OR,1,NaN,NaN,...,579.4327,0.700997,49.15190,189.99160,0,0.000000,0.000000,0.000000,0,0.0
9057,14400000,"CHETCO RIVER NEAR BROOKINGS, OR",702.63450,17,42.123443,-124.187311,OR,1,yes,NaN,...,633.4462,0.610234,43.64037,16.46503,0,0.000000,0.000000,0.000000,0,0.0
9065,402114105350101,"BIG THOMPSON BL MORAINE PARK NR ESTES PARK, CO",104.76990,10L,40.353873,-105.584168,CO,3,NaN,yes,...,358.7618,0.678119,65.25297,4.94352,0,0.000000,0.000000,0.000000,0,0.0

In [5]:
streamflow = pd.read_csv('/Users/ombadi/Desktop/Mo Files/Research/USGS_streamflow/streamflow_v1.csv')
sites = streamflow.columns[1:]

In [6]:
from datetime import datetime, timedelta

In [7]:
# Fish River near Fort Kent, Maine
# Area = 2252.7 km^2
runoff_data = streamflow[['datetime', '01013500']]

# Import rainfall data, and extrat it for the same watershed 
from scipy.io import loadmat
precip = loadmat('/Users/ombadi/Desktop/Mo Files/Research/PRISM/prism_watershed_av_prcp.mat')['watershed_prcp']

# add site ids
sites = pd.read_csv('/Users/ombadi/Desktop/Mo Files/Research/PRISM/sites.csv')

# change to a dataframe
daily_prc = pd.DataFrame(precip, columns= sites.columns)

# Add datetime, year, month and hy-year
t = np.arange(datetime(1981,1,1), datetime(2023,12,31), timedelta(days=1)).astype(datetime)
daily_prc['datetime'] = t
daily_prc['year'] = pd.DatetimeIndex(daily_prc['datetime']).year
daily_prc['month'] = pd.DatetimeIndex(daily_prc['datetime']).month

# Rainfall data
rainfall_data = daily_prc[['datetime', 'year','01013500']]

In [ ]:
#runoff_data['datetime'] = pd.to_datetime(runoff_data['datetime'])
#runoff_data.dtypes

fish_river_data = rainfall_data.merge(runoff_data, on='datetime', how='inner')
fish_river_data = fish_river_data.rename(columns={"01013500_x": "rainfall", "01013500_y": "runoff"})
fish_river_data = fish_river_data[(fish_river_data['year'] >= 2016) & (fish_river_data['year'] <= 2021)]
fish_river_data.index = np.arange(fish_river_data.shape[0])

fish_river_data.to_csv('/Users/ombadi/Desktop/Mo Files/Teaching/CLIMATE 405/Slides/Lec 10/fish_river.csv', index= False)

fish_river_data.head()